
import { Product } from './types.ts';

export const INITIAL_PRODUCTS: Product[] = [
  // 風乾零食
  { id: 'ad-1', category: '風乾零食', name: '貓咪抗拒不了貓草餅乾 catnip cookie for cat', wholesalePrice: 163, retailPrice: 250 },
  { id: 'ad-2', category: '風乾零食', name: '無雞不可，經典雞胸肉乾 Chicken Breast Jerky', wholesalePrice: 163, retailPrice: 250 },
  { id: 'ad-3', category: '風乾零食', name: '我愛吃鴨鴨，一比一比鴨鴨鴨胸肉乾 Duck Breast Jerky', wholesalePrice: 195, retailPrice: 300 },
  { id: 'ad-4', category: '風乾零食', name: '喀滋喀滋鴨氣管，毛孩專屬鴨氣管 Duck Trachea', wholesalePrice: 137, retailPrice: 210 },
  { id: 'ad-5', category: '風乾零食', name: '控制熱量好選擇，鴨鴨繞南瓜 Duck Around Pumpkin', wholesalePrice: 169, retailPrice: 260 },
  { id: 'ad-6', category: '風乾零食', name: '控制熱量好選擇，雞雞繞南瓜 Chicken Around Pumpkin', wholesalePrice: 163, retailPrice: 250 },
  { id: 'ad-7', category: '風乾零食', name: '夢幻星星零食，秋葵鴨肉肉 Okra Duck', wholesalePrice: 169, retailPrice: 260 },
  { id: 'ad-8', category: '風乾零食', name: '夢幻星星零食，秋葵雞肉肉 Okra Chicken', wholesalePrice: 163, retailPrice: 250 },
  { id: 'ad-9', category: '風乾零食', name: '補充膳食纖維，小雞繞紅蘿蔔 Chicken Around Red Radish', wholesalePrice: 195, retailPrice: 300 },
  { id: 'ad-10', category: '風乾零食', name: '健康肉餅，黃金薑黃雞肉餅 Turmeric Chicken', wholesalePrice: 163, retailPrice: 250 },
  { id: 'ad-11', category: '風乾零食', name: '健康肉餅，黃金薑黃鴨肉餅 Turmeric Duck', wholesalePrice: 195, retailPrice: 300 },
  { id: 'ad-12', category: '風乾零食', name: '營養均衡，紅藜麥鴨肉條 Red Quinoa Duck Strips', wholesalePrice: 163, retailPrice: 250 },
  { id: 'ad-13', category: '風乾零食', name: '營養均衡，紅藜麥雞肉條 Red Quinoa Chicken Strips', wholesalePrice: 130, retailPrice: 200 },
  { id: 'ad-14', category: '風乾零食', name: '牛肉塊 Beef Chunks', wholesalePrice: 195, retailPrice: 300 },
  { id: 'ad-15', category: '風乾零食', name: '藍莓芝士雞肉餅 Blueberry Cheese Chicken Patty', wholesalePrice: 195, retailPrice: 300 },
  { id: 'ad-16', category: '風乾零食', name: '蘋果雞肉餅 Apple chichen', wholesalePrice: 195, retailPrice: 300 },
  { id: 'ad-17', category: '風乾零食', name: '迷迭香牛肉餅 Rosemary Steak', wholesalePrice: 137, retailPrice: 210 },
  { id: 'ad-18', category: '風乾零食', name: '羅勒雞肉條 Sweet Basil Chicken', wholesalePrice: 130, retailPrice: 200 },
  { id: 'ad-19', category: '風乾零食', name: '百里香鴨肉 Thyme Duck', wholesalePrice: 137, retailPrice: 210 },
  { id: 'ad-20', category: '風乾零食', name: '經典牛筋片 Beef Tendon', wholesalePrice: 195, retailPrice: 300 },
  { id: 'ad-21', category: '風乾零食', name: '丁香魚小魚乾 Clove Fish', wholesalePrice: 117, retailPrice: 180 },
  { id: 'ad-22', category: '風乾零食', name: '鬆餅雞肉肉-芝芝藍莓 Chichen Waffle Bluebreey Cheese', wholesalePrice: 163, retailPrice: 250 },
  { id: 'ad-23', category: '風乾零食', name: '鬆餅雞肉肉-蔬菜 Chichen Waffle Vegetable', wholesalePrice: 163, retailPrice: 250 },
  { id: 'ad-24', category: '風乾零食', name: '鬆餅雞肉肉-鴨鴨芝芝藍莓 Duck Waffle Blueberry Cheese', wholesalePrice: 163, retailPrice: 250 },
  { id: 'ad-25', category: '風乾零食', name: '雞肉鬆鬆 chicken floss', wholesalePrice: 130, retailPrice: 200 },

  // 凍乾零食
  { id: 'fd-1', category: '凍乾零食', name: '嗷嗚原形脆，雞小方 Freeze Dried Chicken', wholesalePrice: 163, retailPrice: 250 },
  { id: 'fd-2', category: '凍乾零食', name: '嗷嗚原形脆，雞大排 Freeze Dried Chicken Breast', wholesalePrice: 163, retailPrice: 250 },
  { id: 'fd-3', category: '凍乾零食', name: '嗷嗚原形脆，雞小胗 Freeze-Dried Chicken Gizzards', wholesalePrice: 137, retailPrice: 210 },
  { id: 'fd-4', category: '凍乾零食', name: '嗷嗚原形脆，雞皇冠 Freeze-Dried Chicken Combs', wholesalePrice: 137, retailPrice: 210 },
  { id: 'fd-5', category: '凍乾零食', name: '嗷嗚原形脆，雞細條 Freeze-Dried Chicken Tenders', wholesalePrice: 163, retailPrice: 250 },
  { id: 'fd-6', category: '凍乾零食', name: '嗷嗚原形脆，鴨細條 Freeze-Dried Duck Tenders', wholesalePrice: 182, retailPrice: 280 },
  { id: 'fd-7', category: '凍乾零食', name: '嗷嗚原形脆，脆鴨酥 Freeze-Dried Duck Trachea', wholesalePrice: 137, retailPrice: 210 },
  { id: 'fd-8', category: '凍乾零食', name: '嗷嗚原形脆，鴨小舌 Freeze-Dried Duck Tongue', wholesalePrice: 163, retailPrice: 250 },
  { id: 'fd-9', category: '凍乾零食', name: '嗷嗚原形脆，牛小方 Freeze-Dried Beef Cubes', wholesalePrice: 182, retailPrice: 280 },
  { id: 'fd-10', category: '凍乾零食', name: '嗷嗚原形脆，羊小方 Freeze-Dried Lamb Cubes', wholesalePrice: 182, retailPrice: 280 },
  { id: 'fd-11', category: '凍乾零食', name: '嗷嗚原形脆，鮭小方 Freeze-Dried Salmon Cubes', wholesalePrice: 195, retailPrice: 300 },
  { id: 'fd-12', category: '凍乾零食', name: '嗷嗚原形脆，鮭大排 Freeze-Dried Salmon Fillet Slice', wholesalePrice: 195, retailPrice: 300 },
  { id: 'fd-13', category: '凍乾零食', name: '嗷嗚原形脆，丁小魚 Freeze-Dried Clove Fish', wholesalePrice: 182, retailPrice: 280 },
  { id: 'fd-14', category: '凍乾零食', name: '嗷嗚原形脆，小蝦蝦 Freeze-Dried Shrimp', wholesalePrice: 182, retailPrice: 280 },
  { id: 'fd-15', category: '凍乾零食', name: '嗷嗚原形脆，活力羊菜方 Freeze-Dried Lamb & Veggie Cubes', wholesalePrice: 221, retailPrice: 340 },
  { id: 'fd-16', category: '凍乾零食', name: '嗷嗚原形脆，強健牛菜方 Freeze-Dried Beef & Veggie Cubes', wholesalePrice: 221, retailPrice: 340 },
  { id: 'fd-17', category: '凍乾零食', name: '嗷嗚原形脆，腸胃雞菜方 Freeze-Dried Chicken & Veggie Cubes', wholesalePrice: 221, retailPrice: 340 },
  { id: 'fd-18', category: '凍乾零食', name: '嗷嗚原形脆，元氣鴨菜方 Freeze-Dried Duck & Veggie Cubes', wholesalePrice: 221, retailPrice: 340 },
  { id: 'fd-19', category: '凍乾零食', name: '嗷嗚原形脆，蔬菜纖方 Freeze-Dried Seasonal Veggie Cubes', wholesalePrice: 208, retailPrice: 320 },

  // 用品
  { id: 'sup-1', category: '用品', name: '狗狗慢食墊-蜜桃粉', wholesalePrice: 200, retailPrice: 310 },
  { id: 'sup-2', category: '用品', name: '狗狗慢食墊-石灰藍', wholesalePrice: 200, retailPrice: 310 },
  { id: 'sup-3', category: '用品', name: '狗狗慢食墊-蜂蜜黃', wholesalePrice: 200, retailPrice: 310 },
  { id: 'sup-4', category: '用品', name: '狗狗慢食墊-灰草綠', wholesalePrice: 200, retailPrice: 310 },
  { id: 'sup-5', category: '用品', name: '貓薄荷魚玩具', wholesalePrice: 90, retailPrice: 150 },
  { id: 'sup-6', category: '用品', name: '冰淇淋綿綿球', wholesalePrice: 250, retailPrice: 350 },
  { id: 'sup-7', category: '用品', name: '矽膠吸盤餐盤附勺子-小鴨黃', wholesalePrice: 200, retailPrice: 425 },
  { id: 'sup-8', category: '用品', name: '矽膠吸盤餐盤附勺子-寶寶藍', wholesalePrice: 200, retailPrice: 425 },
  { id: 'sup-9', category: '用品', name: '矽膠吸盤餐盤附勺子-蜜桃粉', wholesalePrice: 200, retailPrice: 425 },
  { id: 'sup-10', category: '用品', name: '矽膠吸盤餐盤附勺子-煙灰綠', wholesalePrice: 200, retailPrice: 425 },
  { id: 'sup-11', category: '用品', name: '矽膠吸盤餐盤-奶白', wholesalePrice: 200, retailPrice: 425 },
  { id: 'sup-12', category: '用品', name: '牽繩-大狗狗-粉-140cm/2cm', wholesalePrice: 450, retailPrice: 720 },
  { id: 'sup-13', category: '用品', name: '牽繩-大狗狗-藍', wholesalePrice: 450, retailPrice: 720 },
  { id: 'sup-14', category: '用品', name: '牽繩-大狗狗-黑加侖', wholesalePrice: 450, retailPrice: 720 },
  { id: 'sup-15', category: '用品', name: '牽繩-大狗狗-黑', wholesalePrice: 450, retailPrice: 720 },
  { id: 'sup-16', category: '用品', name: '牽繩-大狗狗-紫', wholesalePrice: 450, retailPrice: 720 },
  { id: 'sup-17', category: '用品', name: '牽繩-大狗狗-橘', wholesalePrice: 450, retailPrice: 720 },
  { id: 'sup-18', category: '用品', name: '牽繩-大狗狗-綠', wholesalePrice: 450, retailPrice: 720 },
  { id: 'sup-19', category: '用品', name: '牽繩-小狗狗-咖啡色-150cm/8mm', wholesalePrice: 600, retailPrice: 720 },
  { id: 'sup-20', category: '用品', name: '牽繩-小狗狗-紫色', wholesalePrice: 600, retailPrice: 720 },
  { id: 'sup-21', category: '用品', name: '牽繩-小狗狗-綠色', wholesalePrice: 600, retailPrice: 720 },
  { id: 'sup-22', category: '用品', name: '短牽繩-大狗狗-粉 70cm', wholesalePrice: 400, retailPrice: 620 },
  { id: 'sup-23', category: '用品', name: '短牽繩-大狗狗-藍', wholesalePrice: 400, retailPrice: 620 },
  { id: 'sup-24', category: '用品', name: '短牽繩-大狗狗-紫', wholesalePrice: 400, retailPrice: 620 },
  { id: 'sup-25', category: '用品', name: '短牽繩-大狗狗-黑', wholesalePrice: 400, retailPrice: 620 },
  { id: 'sup-26', category: '用品', name: '防暴衝胸背-黑S', wholesalePrice: 500, retailPrice: 1200 },
  { id: 'sup-27', category: '用品', name: '防暴衝胸背-黑M', wholesalePrice: 500, retailPrice: 1200 },
  { id: 'sup-28', category: '用品', name: '防暴衝胸背-黑L', wholesalePrice: 500, retailPrice: 1200 },
  { id: 'sup-29', category: '用品', name: '手工逗貓棒 替換頭１', wholesalePrice: 80, retailPrice: 250 },
  { id: 'sup-30', category: '用品', name: '零食保鮮罐-淺灰粉-S-200ml', wholesalePrice: 180, retailPrice: 290 },
  { id: 'sup-31', category: '用品', name: '零食保鮮罐-淺灰粉-M-300ml', wholesalePrice: 190, retailPrice: 390 },
  { id: 'sup-32', category: '用品', name: '零食保鮮罐-淺灰粉-L-600ml', wholesalePrice: 200, retailPrice: 490 },
  { id: 'sup-33', category: '用品', name: '零食保鮮罐-芥末黃-S', wholesalePrice: 180, retailPrice: 290 },
  { id: 'sup-34', category: '用品', name: '零食保鮮罐-芥末黃-M', wholesalePrice: 190, retailPrice: 390 },
  { id: 'sup-35', category: '用品', name: '零食保鮮罐-芥末黃-L', wholesalePrice: 200, retailPrice: 490 },
  { id: 'sup-36', category: '用品', name: '零食保鮮罐-嫩草綠-S', wholesalePrice: 180, retailPrice: 290 },
  { id: 'sup-37', category: '用品', name: '零食保鮮罐-嫩草綠-M', wholesalePrice: 190, retailPrice: 390 },
  { id: 'sup-38', category: '用品', name: '零食保鮮罐-嫩草綠-L', wholesalePrice: 200, retailPrice: 490 },
  { id: 'sup-39', category: '用品', name: '零食保鮮罐-淡海藍-S', wholesalePrice: 180, retailPrice: 290 },
  { id: 'sup-40', category: '用品', name: '零食保鮮罐-淡海藍-M', wholesalePrice: 190, retailPrice: 390 },
  { id: 'sup-41', category: '用品', name: '零食保鮮罐-淡海藍-L', wholesalePrice: 200, retailPrice: 490 },
  { id: 'sup-42', category: '用品', name: '錐形伊莉莎白圈-奶酪黄-S', wholesalePrice: 320, retailPrice: 600 },
  { id: 'sup-43', category: '用品', name: '錐形伊莉莎白圈-奶酪黄-M', wholesalePrice: 350, retailPrice: 650 },
  { id: 'sup-44', category: '用品', name: '錐形伊莉莎白圈-奶酪黄-L', wholesalePrice: 350, retailPrice: 650 },
  { id: 'sup-45', category: '用品', name: '錐形伊莉莎白圈-奶酪黄-XL', wholesalePrice: 400, retailPrice: 720 },
  { id: 'sup-46', category: '用品', name: '錐形伊莉莎白圈-抹茶綠-S', wholesalePrice: 320, retailPrice: 600 },
  { id: 'sup-47', category: '用品', name: '錐形伊莉莎白圈-抹茶綠-M', wholesalePrice: 350, retailPrice: 650 },
  { id: 'sup-48', category: '用品', name: '錐形伊莉莎白圈-抹茶綠-L', wholesalePrice: 350, retailPrice: 650 },
  { id: 'sup-49', category: '用品', name: '錐形伊莉莎白圈-抹茶綠-XL', wholesalePrice: 400, retailPrice: 720 },
  { id: 'sup-50', category: '用品', name: '花朵伊莉莎白圈-夢幻紫-S', wholesalePrice: 325, retailPrice: 680 },
  { id: 'sup-51', category: '用品', name: '花朵伊莉莎白圈-夢幻紫-M', wholesalePrice: 345, retailPrice: 680 },
  { id: 'sup-52', category: '用品', name: '花朵伊莉莎白圈-夢幻紫-L', wholesalePrice: 355, retailPrice: 680 },
  { id: 'sup-53', category: '用品', name: '花朵伊莉莎白圈-南瓜橙-S', wholesalePrice: 325, retailPrice: 680 },
  { id: 'sup-54', category: '用品', name: '花朵伊莉莎白圈-南瓜橙-M', wholesalePrice: 345, retailPrice: 680 },
  { id: 'sup-55', category: '用品', name: '花朵伊莉莎白圈-南瓜橙-L', wholesalePrice: 355, retailPrice: 680 },
  { id: 'sup-56', category: '用品', name: '花朵伊莉莎白圈-天空藍-S', wholesalePrice: 325, retailPrice: 680 },
  { id: 'sup-57', category: '用品', name: '花朵伊莉莎白圈-天空藍-M', wholesalePrice: 345, retailPrice: 680 },
  { id: 'sup-58', category: '用品', name: '花朵伊莉莎白圈-天空藍-L', wholesalePrice: 355, retailPrice: 680 },
  { id: 'sup-59', category: '用品', name: '花朵伊莉莎白圈-嫩草綠-S', wholesalePrice: 325, retailPrice: 680 },
  { id: 'sup-60', category: '用品', name: '花朵伊莉莎白圈-嫩草綠-M', wholesalePrice: 345, retailPrice: 680 },
  { id: 'sup-61', category: '用品', name: '花朵伊莉莎白圈-嫩草綠-L', wholesalePrice: 355, retailPrice: 680 },
  { id: 'sup-62', category: '用品', name: '自製大狗花朵圈-粉-M', wholesalePrice: 500, retailPrice: 680 },
  { id: 'sup-63', category: '用品', name: '自製大狗花朵圈-粉-L', wholesalePrice: 650, retailPrice: 820 },
  { id: 'sup-64', category: '用品', name: '自製大狗花朵圈-粉-XL', wholesalePrice: 780, retailPrice: 960 },
  { id: 'sup-65', category: '用品', name: '自製大狗花朵圈-粉-XXL', wholesalePrice: 1080, retailPrice: 1200 },
  { id: 'sup-66', category: '用品', name: '自製大狗花朵圈-藍-M', wholesalePrice: 500, retailPrice: 680 },
  { id: 'sup-67', category: '用品', name: '自製大狗花朵圈-藍-L', wholesalePrice: 650, retailPrice: 820 },
  { id: 'sup-68', category: '用品', name: '自製大狗花朵圈-藍-XL', wholesalePrice: 780, retailPrice: 960 },
  { id: 'sup-69', category: '用品', name: '自製大狗花朵圈-藍-XXL', wholesalePrice: 1080, retailPrice: 1200 },
  { id: 'sup-70', category: '用品', name: '自製大狗花朵圈-綠-M', wholesalePrice: 500, retailPrice: 680 },
  { id: 'sup-71', category: '用品', name: '自製大狗花朵圈-綠-L', wholesalePrice: 650, retailPrice: 820 },
  { id: 'sup-72', category: '用品', name: '自製大狗花朵圈-綠-XL', wholesalePrice: 780, retailPrice: 960 },
  { id: 'sup-73', category: '用品', name: '自製大狗花朵圈-綠-XXL', wholesalePrice: 1080, retailPrice: 1200 },
  { id: 'sup-74', category: '用品', name: '甜甜圈陶瓷寵物碗單層奶油白', wholesalePrice: 225, retailPrice: 580 },
  { id: 'sup-75', category: '用品', name: '甜甜圈陶瓷寵物碗單層小鴨黃', wholesalePrice: 225, retailPrice: 580 },
  { id: 'sup-76', category: '用品', name: '甜甜圈陶瓷寵物碗單層芋泥紫', wholesalePrice: 225, retailPrice: 580 },
  { id: 'sup-77', category: '用品', name: '雙頭轉接牽繩-黑', wholesalePrice: 350, retailPrice: 880 },
  { id: 'sup-78', category: '用品', name: '雙頭轉接牽繩-粉', wholesalePrice: 350, retailPrice: 880 },
  { id: 'sup-79', category: '用品', name: '雙頭轉接牽繩-紫', wholesalePrice: 350, retailPrice: 880 },
  { id: 'sup-80', category: '用品', name: '雙頭轉接牽繩-黑白', wholesalePrice: 350, retailPrice: 880 },
  { id: 'sup-81', category: '用品', name: '棉花糖撿便器-霓虹果醬粉紫', wholesalePrice: 185, retailPrice: 210 },
  { id: 'sup-82', category: '用品', name: '棉花糖撿便器-抹茶椰林粉白', wholesalePrice: 185, retailPrice: 210 },
  { id: 'sup-83', category: '用品', name: '棉花糖撿便器-焦糖海鹽藍白', wholesalePrice: 185, retailPrice: 210 },
  { id: 'sup-84', category: '用品', name: '棉花糖撿便器-銀色', wholesalePrice: 185, retailPrice: 210 },
  { id: 'sup-85', category: '用品', name: '棉花糖撿便器-黑粉', wholesalePrice: 185, retailPrice: 210 },
  { id: 'sup-86', category: '用品', name: '超耐咬狗骨頭-紅色', wholesalePrice: 90, retailPrice: 200 },
  { id: 'sup-87', category: '用品', name: '超耐咬狗骨頭-藍色', wholesalePrice: 90, retailPrice: 200 },
  { id: 'sup-88', category: '用品', name: '超耐咬狗骨頭-綠色', wholesalePrice: 90, retailPrice: 200 },
  { id: 'sup-89', category: '用品', name: '超耐咬狗骨頭-紫色', wholesalePrice: 90, retailPrice: 200 },
  { id: 'sup-90', category: '用品', name: '超耐咬狗骨頭-黃色', wholesalePrice: 90, retailPrice: 200 },
  { id: 'sup-91', category: '用品', name: '超耐咬狗骨頭-扣環', wholesalePrice: 90, retailPrice: 200 },
  { id: 'sup-92', category: '用品', name: 'BITE ME 土撥鼠', wholesalePrice: 580, retailPrice: 880 },
  { id: 'sup-93', category: '用品', name: 'BITE ME 浣熊', wholesalePrice: 580, retailPrice: 880 },
  { id: 'sup-94', category: '用品', name: 'BITE ME 松鼠', wholesalePrice: 220, retailPrice: 380 },
  { id: 'sup-95', category: '用品', name: 'BITE ME 老鼠', wholesalePrice: 220, retailPrice: 380 },
  { id: 'sup-96', category: '用品', name: 'BITE ME 曲奇', wholesalePrice: 280, retailPrice: 420 },
  { id: 'sup-97', category: '用品', name: 'DINGDOG 捲餅', wholesalePrice: 480, retailPrice: 680 },
  { id: 'sup-98', category: '用品', name: 'DINGDOG 壽司', wholesalePrice: 380, retailPrice: 680 },
  { id: 'sup-99', category: '用品', name: 'DINGDOG 蔥', wholesalePrice: 320, retailPrice: 680 },
  { id: 'sup-100', category: '用品', name: 'DINGDOG 薯條', wholesalePrice: 380, retailPrice: 580 },
  { id: 'sup-101', category: '用品', name: 'DINGDOG 炸蝦', wholesalePrice: 320, retailPrice: 680 },
  { id: 'sup-102', category: '用品', name: 'DINGDOG 大漢堡', wholesalePrice: 420, retailPrice: 680 },
  { id: 'sup-103', category: '用品', name: 'DINGDOG 小漢堡', wholesalePrice: 365, retailPrice: 580 },
  { id: 'sup-104', category: '用品', name: 'DINGDOG 鮪魚罐頭', wholesalePrice: 365, retailPrice: 580 },
  { id: 'sup-105', category: '用品', name: 'DINGDOG 草莓果醬', wholesalePrice: 380, retailPrice: 580 },
  { id: 'sup-106', category: '用品', name: 'DINGDOG 橘子果醬', wholesalePrice: 380, retailPrice: 580 },
  { id: 'sup-107', category: '用品', name: 'OKTK 毛孩衣 粉綠 L', wholesalePrice: 820, retailPrice: 1380 },
  { id: 'sup-108', category: '用品', name: 'OKTK 毛孩衣 粉綠 XL', wholesalePrice: 820, retailPrice: 1380 },
  { id: 'sup-109', category: '用品', name: 'OKTK 毛孩衣 粉綠 2XL', wholesalePrice: 820, retailPrice: 1380 },
  { id: 'sup-110', category: '用品', name: 'OKTK 毛孩衣 粉綠 3XL', wholesalePrice: 820, retailPrice: 1380 },
  { id: 'sup-111', category: '用品', name: 'OKTK 毛孩衣 粉綠 5XL', wholesalePrice: 820, retailPrice: 1380 },
  { id: 'sup-112', category: '用品', name: 'OKTK 毛孩衣 粉綠 6XL', wholesalePrice: 820, retailPrice: 1380 },
  { id: 'sup-113', category: '用品', name: 'OKTK 毛孩衣 黑白 L', wholesalePrice: 820, retailPrice: 1380 },
  { id: 'sup-114', category: '用品', name: 'OKTK 毛孩衣 黑白 XL', wholesalePrice: 820, retailPrice: 1380 },
  { id: 'sup-115', category: '用品', name: 'OKTK 毛孩衣 黑白 2XL', wholesalePrice: 820, retailPrice: 1380 },
  { id: 'sup-116', category: '用品', name: 'OKTK 毛孩衣 黑白 3XL', wholesalePrice: 820, retailPrice: 1380 },
  { id: 'sup-117', category: '用品', name: 'OKTK 毛孩衣 黑白 5XL', wholesalePrice: 820, retailPrice: 1380 },
  { id: 'sup-118', category: '用品', name: 'OKTK 毛孩衣 黑白 6XL', wholesalePrice: 820, retailPrice: 1380 },
];
